paths:
  web: "McAuley-Lab/Amazon-Reviews-2023"
  source: "./data/raw/"
  connection: "postgresql://postgres:12345678@localhost:5432/dsa3101"
  data: "./data/"
  exports: "./exports/"

sql:
  db: "./sql/create_schema.sql"
  queries: "./sql/queries/"
  
